export default function DataProtection() {
    return (
<div class="text-white">
<h1 className="text-5xl">Privacy policy</h1>
    <h2>1. data privacy at a glance</h2>
    <h3>General information</h3> 
    <p>The following information provides a simple overview of what happens to your personal data when you visit this website. 
        Personal data is any data that can be used to identify you personally. 
        Detailed information on the subject of data protection can be found in our data protection declaration listed below this text.
    </p>


<h3>Data collection on this website</h3> 
<h4>Who is responsible for data collection on this website?</h4> 
<p>Data processing on this website is carried out by the website operator. 
    You can find the operator's contact details in the 
    "Information on the controller" section of this privacy policy.</p> 

<h4>How do we collect your data?</h4> 
<p>Your data is collected
collected by you communicating it to us. This may, for example, be data that you enter in a contact form.
</p> 
<p>Other data is collected automatically or with your consent by our IT systems when you visit the website. 
    This is primarily technical data (e.g. internet browser, operating system or time of page view). 
    This data is collected automatically as soon as you enter this website.</p> 
    

<h4>What do we use your data for?</h4> 
<p>A portion of the data is collected to ensure a fault-free provision of the website. Other data can be used to analyze your user behavior.</p>

<h4>What rights do you have regarding your data?</h4>
<p>You have the right at any time to obtain information about the origin, recipient, and purpose of your stored personal data free of charge. You also have the right to request the correction or deletion of this data. If you have given consent to data processing, you can revoke this consent at any time for the future. Moreover, you have the right to request the restriction of the processing of your personal data under certain circumstances. Furthermore, you have the right to lodge a complaint with the competent supervisory authority.</p> <p>For this purpose, as well as for further questions on the subject of data protection, you can contact us at any time.</p>
<h3>Analysis tools and tools from third-party providers</h3> <p>When visiting our website, your surfing behavior can be statistically evaluated. This is mainly done with so-called analysis programs.</p>
<p>Detailed information about these analysis programs can be found in the following privacy statement.</p>
<h2>2. Hosting</h2>
<p>We host the contents of our website with the following provider:</p>
<h3>IONOS</h3> <p>The provider is IONOS SE, Elgendorfer Str. 57, 56410 Montabaur (hereinafter IONOS). When you visit our website, IONOS collects various log files including your IP addresses. For details, please see the IONOS privacy policy: <a href="https://www.ionos.de/terms-gtc/terms-privacy" target="_blank" rel="noopener noreferrer">https://www.ionos.de/terms-gtc/terms-privacy</a>.</p>
<p>The use of IONOS is based on Art. 6 para. 1 lit. f GDPR. We have a legitimate interest in the most reliable presentation of our website. If a corresponding consent has been requested, the processing is carried out exclusively on the basis of Art. 6 para. 1 lit. a GDPR and § 25 para. 1 TTDSG, insofar as the consent includes the storage of cookies or access to information in the user's end device (e.g., device fingerprinting) within the meaning of the TTDSG. The consent can be revoked at any time.</p>
<h4>Data processing agreement</h4> <p>We have concluded a data processing agreement (DPA) for the use of the above-mentioned service. This is a data protection agreement required by law, which ensures that this processes the personal data of our website visitors only according to our instructions and in compliance with the GDPR.</p>
<h2>3. General information and mandatory information</h2>
<h3>Data protection</h3> <p>The operators of these pages take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance with the statutory data protection regulations and this privacy policy.</p> <p>When you use this website, various personal data are collected. Personal data are data with which you can be personally identified. This privacy policy explains what data we collect and what we use it for. It also explains how and for what purpose this happens.</p> <p>Please note that data transmission over the Internet (e.g., when communicating by email) may have security gaps. Complete protection of data against access by third parties is not possible.</p>
<h3>Note on the responsible entity</h3> <p>The responsible entity for data processing on this website is:</p> <p>Andreas Glashauser<br />
Akazienring 43<br />
94522 Wallersdorf</p>
<p>Email: a.andreasglashauser@gmail.com</p>
<p>The responsible entity is the natural or legal person who alone or jointly with others decides on the purposes and means of processing personal data (e.g., names, email addresses, etc.).</p>
<h3>Storage duration</h3> <p>Unless a more specific storage period has been mentioned within this privacy policy, your personal data will remain with us until the purpose for data processing no longer applies. If you assert a justified request for deletion or revoke consent to data processing, your data will be deleted, unless we have other legally permissible reasons for storing your personal data (e.g., tax or commercial law retention periods); in the latter case, deletion will take place after these reasons cease to apply.</p>
<h3>General information on the legal bases for data processing on this website</h3> <p>If you have given your consent to data processing, we process your personal data based on Art. 6 para. 1 lit. a GDPR or Art. 9 para. 2 lit. a GDPR if special categories of data according to Art. 9 para. 1 GDPR are processed. In the event of explicit consent to the transfer of personal data to third countries, data processing is also based on Art. 49 para. 1 lit. a GDPR. If you have consented to the storage of cookies or to access information into your end device (e.g., via device fingerprinting), the data processing is additionally based on § 25 para. 1 TTDSG. The consent can be revoked at any time. If your data is required for the performance of a contract or for carrying out pre-contractual measures, we process your data based on Art. 6 para. 1 lit. b GDPR. Furthermore, we process your data if this is necessary for the fulfillment of a legal obligation on the basis of Art. 6 para. 1 lit. c GDPR. Data processing may also take place on the basis of our legitimate interest according to Art. 6 para. 1 lit. f GDPR. The respective legal bases applicable in each case are provided in the following paragraphs of this privacy policy.</p>
<h3>Recipients of personal data</h3> <p>As part of our business activities, we cooperate with various external entities. In some cases, this also requires the transfer of personal data to these external entities. We only pass on personal data to external entities if this is necessary for the fulfillment of a contract, if we are legally obliged to do so (e.g., transfer of data to tax authorities), if we have a legitimate interest under Art. 6 para. 1 lit. f GDPR in the transfer, or if another legal basis allows the data transfer. When using processors, we only pass on personal data of our customers based on a valid contract for data processing. In the case of joint processing, a contract for joint processing is concluded.</p>
<h3>Revocation of your consent to data processing</h3> <p>Many data processing operations are only possible with your express consent. You can revoke consent you have already given at any time. The legality of the data processing carried out until the revocation remains unaffected by the revocation.</p>
<h3>Right to object to the collection of data in special cases and to direct advertising (Art. 21 GDPR)</h3> <p>IF DATA PROCESSING IS BASED ON ART. 6 PARA. 1 LIT. E OR F GDPR, YOU HAVE THE RIGHT AT ANY TIME TO OBJECT TO THE PROCESSING OF YOUR PERSONAL DATA FOR REASONS ARISING FROM YOUR PARTICULAR SITUATION; THIS ALSO APPLIES TO PROFILING BASED ON THESE PROVISIONS. THE RESPECTIVE LEGAL BASIS ON WHICH A PROCESSING IS BASED IS TAKEN FROM THIS PRIVACY POLICY. IF YOU OBJECT, WE WILL NO LONGER PROCESS YOUR AFFECTED PERSONAL DATA, UNLESS WE CAN DEMONSTRATE COMPELLING LEGITIMATE GROUNDS FOR THE PROCESSING THAT OVERRIDE YOUR INTERESTS, RIGHTS, AND FREEDOMS, OR IF THE PROCESSING IS FOR THE ESTABLISHMENT, EXERCISE, OR DEFENSE OF LEGAL CLAIMS (OBJECTION ACCORDING TO ART. 21 PARA. 1 GDPR).</p> <p>IF YOUR PERSONAL DATA IS PROCESSED FOR DIRECT ADVERTISING PURPOSES, YOU HAVE THE RIGHT TO OBJECT AT ANY TIME TO THE PROCESSING OF PERSONAL DATA CONCERNING YOU FOR SUCH ADVERTISING; THIS ALSO APPLIES TO PROFILING TO THE EXTENT THAT IT IS ASSOCIATED WITH SUCH DIRECT ADVERTISING. IF YOU OBJECT, YOUR PERSONAL DATA WILL SUBSEQUENTLY NO LONGER BE USED FOR DIRECT ADVERTISING PURPOSES (OBJECTION ACCORDING TO ART. 21 PARA. 2 GDPR).</p>
<h3>Right to file complaints with regulatory authorities</h3> <p>In the case of breaches of the GDPR, the persons concerned have a right to lodge a complaint with a regulatory authority, in particular in the Member State of their habitual residence, place of work or place of the alleged infringement. The right to lodge a complaint is without prejudice to other administrative or judicial remedies.</p>
<h3>Right to data portability</h3> <p>You have the right to have data that we process based on your consent or in fulfillment of a contract automatically delivered to yourself or to a third party in a standard, machine-readable format. If you require the direct transfer of data to another responsible party, this will only be done to the extent technically feasible.</p>
<h3>Information, correction, and deletion</h3> <p>Within the framework of the applicable legal provisions, you have the right at any time to free information about your stored personal data, their origin and recipient and the purpose of the data processing and, if necessary, a right to correction or deletion of this data. For this purpose, as well as for further questions on the subject of personal data, you can contact us at any time.</p>
<h3>Right to request processing restrictions</h3> <p>You have the right to request the restriction of the processing of your personal data. You can contact us at any time for this purpose. The right to request processing restrictions applies in the following cases:</p> <ul> <li>If you dispute the accuracy of your personal data stored with us, we usually need time to verify this. For the duration of the review, you have the right to request the restriction of the processing of your personal data.</li> <li>If the processing of your personal data was/is unlawful, you can request the restriction of data processing instead of deletion.</li> <li>If we no longer need your personal data, but you need them to exercise, defend or assert legal claims, you have the right to request the restriction of the processing of your personal data instead of deletion.</li> <li>If you have filed an objection under Art. 21 para. 1 GDPR, a balance must be struck between your interests and ours. As long as it has not yet been determined whose interests prevail, you have the right to request the restriction of the processing of your personal data.</li> </ul>
<p>If you have restricted the processing of your personal data, these data – apart from their storage – may only be processed with your consent or for the establishment, exercise, or defense of legal claims or for the protection of the rights of another natural or juristic person or for reasons of important public interest of the European Union or a Member State.</p>
<h3>SSL or TLS encryption</h3> <p>This site uses SSL or TLS encryption for security reasons and to protect the transmission of confidential content, such as orders or inquiries, which you send to us as the site operator. You can recognize an encrypted connection by the fact that the address line of the browser changes from "http://" to "https://" and by the lock symbol in your browser line.</p> <p>If SSL or TLS encryption is activated, the data you transmit to us cannot be read by third parties.</p>
<h2>4. Data collection on this website</h2>
<h3>Cookies</h3> <p>Our website uses so-called "cookies". Cookies are small text files and do not cause any damage to your device. They are either stored temporarily for the duration of a session (session cookies) or permanently (permanent cookies) on your device. Session cookies are automatically deleted after your visit. Permanent cookies remain stored on your device until you delete them yourself or an automatic deletion is carried out by your web browser.</p> <p>Cookies can be set by us (first-party cookies) or by third-party companies (so-called third-party cookies). Third-party cookies enable certain services to be integrated into websites (e.g., cookies for processing payment services).</p> <p>Cookies have various functions. Many cookies are technically necessary as certain website functions would not work without them (e.g., the shopping cart function or displaying videos). Other cookies can be used to analyze user behavior or for advertising purposes.</p> <p>Cookies that are necessary to carry out the electronic communication process, to provide certain functions you desire (e.g., for the shopping cart function), or to optimize the website (e.g., cookies for measuring the web audience) (necessary cookies), are stored based on Art. 6 para. 1 lit. f GDPR, unless another legal basis is specified. The website operator has a legitimate interest in storing cookies for the technically error-free and optimized provision of its services. If consent to the storage of cookies and similar recognition technologies was requested, the processing is carried out exclusively on this consent basis (Art. 6 para. 1 lit. a GDPR and § 25 para. 1 TTDSG); the consent can be revoked at any time.</p>
<p>You can set your browser to inform you about the setting of cookies and allow cookies only in individual cases, exclude the acceptance of cookies for specific cases or in general, and activate the automatic deletion of cookies when closing the browser. Disabling cookies may limit the functionality of this website.</p>
<p>Which cookies and services are used on this website can be found in this privacy policy.</p>
<h2>5. Newsletter</h2>
<h3>Newsletter data</h3> <p>If you would like to receive the newsletter offered on the website, we require an email address from you, as well as information that allows us to verify that you are the owner of the provided email address and that you agree to receive the newsletter. Further data is not collected or only on a voluntary basis. We use these data exclusively for sending the requested information and do not pass them on to third parties.</p> <p>The processing of the data entered into the newsletter subscription form is based exclusively on your consent (Art. 6 para. 1 lit. a GDPR). You can revoke the consent given for storing the data, the email address, and their use for sending the newsletter at any time, for example, via the "unsubscribe" link in the newsletter. The legality of the already completed data processing operations remains unaffected by the revocation.</p> <p>The data you provide for the purpose of receiving the newsletter will be stored by us or the newsletter service provider until you unsubscribe from the newsletter and will be deleted from the newsletter distribution list after you unsubscribe from the newsletter or after the purpose has ceased to exist. We reserve the right to delete or block email addresses from our newsletter distribution list at our own discretion within the scope of our legitimate interest according to Art. 6 para. 1 lit. f GDPR.</p> <p>Data stored by us for other purposes remain unaffected by this.</p> <p>After you have been removed from the newsletter distribution list, your email address may be stored by us or the newsletter service provider in a blacklist, if this is necessary to prevent future mailings. The data from the blacklist are used only for this purpose and are not merged with other data. This serves both your interest and our interest in complying with the legal requirements for sending newsletters (legitimate interest within the meaning of Art. 6 para. 1 lit. f GDPR). The storage in the blacklist is not limited in time. <strong>You may object to the storage if your interests outweigh our legitimate interest.</strong></p>
<p>Source: <a href="https://www.e-recht24.de">https://www.e-recht24.de</a> </p>

</div>
    )
}