name: Supabase Update

on:
  push:
    paths:
      - 'public/blog/**'
    paths-ignore:
      - 'src/supabase/**'

jobs:
  update-supabase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Convert and Upload Blog Posts
        run: node ./scripts/upload-posts.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
